version: '3.5'

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /media/sf_data/wordpress

  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /media/sf_data/mariadb




services:

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME:      ${MYSQL_HOSTNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports: 
      - "403:403"
    volumes:
      - "wp:/var/www/html"
    networks:
      - app-network
    restart: always
      # TODO depends_on:

