version: '3'
services:

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - backend
    restart: always
    environment:
      dbname:     ${dbname}
      username:   ${username}
      dbpasswd:   ${dbpasswd}
      mysqlhost:  ${mysqlhost}
      rootpw:     ${rootpw}
    env_file:
      - .env

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports: 
      - "403:403"
    volumes:
      - "~/Desktop/inception/nginx:/var/www/html"
    networks:
      - frontend
    restart: always
    # TODO depends_on:

networks:
  backend:
  frontend:
