version: "3.5"

services:

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
        - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - WP_DOMAIN=${WP_DOMAIN}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN=${WP_ADMIN}
        - WP_URL=${WP_URL}
        - WP_USER=${WP_USER}
        - WP_USER_MAIL=${WP_USER_MAIL}
        - WP_USER_PASS=${WP_USER_PASS}
    volumes:
      - db:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env
    init: true
  
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress
      args:
        - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - WP_DOMAIN=${WP_DOMAIN}
        - WP_TITLE=${WP_TITLE}
        - WP_ADMIN=${WP_ADMIN}
        - WP_URL=${WP_URL}
        - WP_USER=${WP_USER}
        - WP_USER_MAIL=${WP_USER_MAIL}
        - WP_USER_PASS=${WP_USER_PASS}
    restart: always
    volumes:
      - wp:/var/www/wordpress
    networks:
      - network
    env_file:
      - .env
    init: true
    
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    volumes:
      - wp:/var/www/wordpress
    networks:
      - network
    restart: always
    init: true
    
networks:
  network: {}

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/max/data/wordpress

  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/max/data/mariadb

