version: "3"

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /media/sf_data/wordpress

  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /media/sf_data/mariadb




services:

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    environment:
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
      MYSQL_HOSTNAME:      ${MYSQL_HOSTNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    env_file:
      - .env

  wordpress:
    build: requirements/nginx
    container_name: wordpress
    volumes:
      - "wp:/var/www/html"
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env
    environment:
      WP_ADMIN:       ${WP_ADMIN}
      WP_ADMIN_PW:    ${WP_ADMIN_PW}
      WP_ADMIN_MAIL:  ${WP_ADMIN_MAIL}
      WP_USER:        ${WP_USER}
      WP_USER_PW:     ${WP_USER_PW}
      WP_USER_EMAIL:  ${WP_USER_MAIL}
      URL:            ${URL}
      TITLE:          ${TITLE}
    depends_on:
      - mariadb

  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports: 
      - "403:403"
    volumes:
      - wp:/var/www/html
    networks:
      - app-network
    depends_on:
      - wordpress
    restart: unless-stopped
